name: Hello
favicon: null
layout_spectrum: 0.771638315403834
typography_spectrum: 0.6219514438416809
title: New Here
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#08090d'
    - '#404e57'
    - '#9e9087'
    - '#bbafb3'
  brandStrength: 0.9390872037038207
  lightness: 0.9081704935524613
  saturation: 0.3353504496626556
  rhythmicContrast: 0.4734604370314628
purpose: []
